/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TestApiController_findAll"];
        put?: never;
        post: operations["TestApiController_createOne"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-api/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TestApiController_findOne"];
        put: operations["TestApiController_updateOne"];
        post?: never;
        delete: operations["TestApiController_removeOne"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateTestDto: {
            /**
             * @description Id postu
             * @example 231
             */
            id: number;
            /**
             * @description Nazov postu
             * @example Moj post
             */
            title: string;
            /**
             * @description Obsah postu
             * @example v tomto poste sa nachadza context
             */
            content: string;
        };
        UpdateDto: {
            /**
             * @description Názov postu
             * @example Aktualizovaný názov
             */
            title?: string;
            /**
             * @description Obsah postu
             * @example Aktualizovaný obsah.
             */
            content?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestApiController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Zoznam vsetkych postov */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTestDto"][];
                };
            };
        };
    };
    TestApiController_createOne: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTestDto"];
            };
        };
        responses: {
            /** @description Post vytvorený */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTestDto"];
                };
            };
        };
    };
    TestApiController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID postu */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Post s id 345 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTestDto"];
                };
            };
            /** @description Post nenájdený */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestApiController_updateOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID postu na aktualizáciu */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDto"];
            };
        };
        responses: {
            /** @description Post aktualizovaný */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTestDto"];
                };
            };
            /** @description Post nenájdený */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TestApiController_removeOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID postu na odstránenie */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Post odstránený */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTestDto"];
                };
            };
            /** @description Post nenájdený */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
